#!/usr/bin/python3
'''Get block by number.
'''

# Import the Python module.
import json
import requests

# Set block number.
NUMBER = 200

# Set the service url.
URL = "https://api.trongrid.io/wallet/getblockbynum"

# Set payload.
PAYLOAD = {"num": NUMBER}

# Initialise the headers.
HEADERS = {
    "Accept": "application/json",
    "Content-Type": "application/json"
}

# ====================
# Main script function
# ====================
def main():
    '''Main script function.'''
    # Get the response from RPC server.
    response = requests.post(URL, json=PAYLOAD, headers=HEADERS)
    # Create a dictionary from the response.
    response = response.json()
    # Create json data from dictionary.
    response_json = json.dumps(response, indent=2)
    # Print result to screen.
    print(response_json)

# Execute script as program or as module.
if __name__ == "__main__":
    # Call the main script function.
    main()
